// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/cachepb/cache.proto
// cSpell:ignore cachepb

package cachepb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRequest 定义 Get 方法的请求参数
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// group 是缓存的命名空间，例如 "scores", "users"
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"` // // 字段编号 1
	// key 是具体的缓存键
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_cachepb_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cachepb_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_cachepb_cache_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// GetResponse 定义 Get 方法的响应
type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// value 是缓存的值，使用 bytes 类型以支持任意二进制数据
	Value         []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_cachepb_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_cachepb_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_cachepb_cache_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_api_cachepb_cache_proto protoreflect.FileDescriptor

const file_api_cachepb_cache_proto_rawDesc = "" +
	"\n" +
	"\x17api/cachepb/cache.proto\x12\acachepb\"4\n" +
	"\n" +
	"GetRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value2>\n" +
	"\n" +
	"GroupCache\x120\n" +
	"\x03Get\x12\x13.cachepb.GetRequest\x1a\x14.cachepb.GetResponseB&Z$DistributedCache/api/cachepb;cachepbb\x06proto3"

var (
	file_api_cachepb_cache_proto_rawDescOnce sync.Once
	file_api_cachepb_cache_proto_rawDescData []byte
)

func file_api_cachepb_cache_proto_rawDescGZIP() []byte {
	file_api_cachepb_cache_proto_rawDescOnce.Do(func() {
		file_api_cachepb_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_cachepb_cache_proto_rawDesc), len(file_api_cachepb_cache_proto_rawDesc)))
	})
	return file_api_cachepb_cache_proto_rawDescData
}

var file_api_cachepb_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_cachepb_cache_proto_goTypes = []any{
	(*GetRequest)(nil),  // 0: cachepb.GetRequest
	(*GetResponse)(nil), // 1: cachepb.GetResponse
}
var file_api_cachepb_cache_proto_depIdxs = []int32{
	0, // 0: cachepb.GroupCache.Get:input_type -> cachepb.GetRequest
	1, // 1: cachepb.GroupCache.Get:output_type -> cachepb.GetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_cachepb_cache_proto_init() }
func file_api_cachepb_cache_proto_init() {
	if File_api_cachepb_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_cachepb_cache_proto_rawDesc), len(file_api_cachepb_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_cachepb_cache_proto_goTypes,
		DependencyIndexes: file_api_cachepb_cache_proto_depIdxs,
		MessageInfos:      file_api_cachepb_cache_proto_msgTypes,
	}.Build()
	File_api_cachepb_cache_proto = out.File
	file_api_cachepb_cache_proto_goTypes = nil
	file_api_cachepb_cache_proto_depIdxs = nil
}
